In [3]:
# Solution to several Eulers, with modification of edges. All based on traversal of a matrix
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt

m = open('matrix.txt')
matrix = m.readlines()
m = [[int(a) for a in line.replace('\n', '').split(',')] for line in matrix]
m = np.array(m)

graph = nx.DiGraph()
for row in range(80):
    for col in range(80):
        graph.add_node((row, col), set=row)
for (row, col) in graph.nodes():
    if (row+1, col) in graph.nodes():
        graph.add_edge((row, col), (row+1, col), weight=m[row+1][col])
    if (row-1, col) in graph.nodes():
        graph.add_edge((row, col), (row-1, col), weight=m[row-1][col])
    if (row, col+1) in graph.nodes():
        graph.add_edge((row, col), (row, col+1), weight=m[row][col+1])
    if (row, col-1) in graph.nodes():
        graph.add_edge((row, col), (row, col-1), weight=m[row][col-1])
path_len = nx.shortest_path_length(graph, (0, 0), (79, 79), weight='weight')
print(path_len+m[0][0])


[[4445 2697 5115 ... 2758 3748 5870]
 [1096   20 1318 ... 4187 9353 9377]
 [9607 7385  521 ... 9515 6385 9230]
 ...
 [2265 8192 1763 ... 7456 5128 5294]
 [2132 8992 8160 ... 5634 1113 5789]
 [5304 5499  564 ... 2751 3406 7981]]
425185
