In [92]:
import numpy as np
from tqdm import tqdm

import networkx as nx
import pandas as pd


In [93]:
SHAPE = 10 ** 7

s = np.zeros(2 * SHAPE, dtype=int)
s[0] = 102022661

for i in tqdm(range(1, 2 * SHAPE)):
    s[i] = (s[i - 1] ** 2) % 998_388_889

s[:10]

100%|██████████| 19999999/19999999 [00:06<00:00, 3081737.75it/s]


array([102022661, 864751430, 661600260, 328965239, 239894592, 387052877,
       504582498, 717196187, 703150034, 193010287])

In [ ]:
x, y = 29567, 33767

In [111]:
x_ser = s.__mod__(x)
y_ser = s.__mod__(y)

In [112]:
print(np.where(x_ser == 0))

(array([       2,        6,       12, ..., 19999981, 19999991, 19999994],
      shape=(2222033,)),)


In [113]:
print(np.where(y_ser == 0))

(array([       2,        6,       12, ..., 19999981, 19999991, 19999994],
      shape=(2222033,)),)


In [ ]:
a = s[::2]
b = s[1::2]


array([102022661, 661600260, 239894592, 504582498, 703150034, 411120915,
       342661968, 434148505, 288426578, 405915867, 422645272, 671266310,
       189963795, 634401362, 594438663, 584139584, 620414078, 309538314,
       234605808, 795062132, 841148860, 319498390, 497335273, 635393015,
       477237222, 477599468, 537704352, 624379838, 305883387, 366268663,
       297920534, 376635308, 423794513, 601475391, 805985826, 251655582,
       135669659, 783743665, 206159982, 546857372, 741107201, 323393108,
       646109054, 910175745, 422721247, 774883101, 860518725, 812895607,
       340592176, 615056156])

In [ ]:
print(np.where(s == ))

(array([2]),)


In [96]:
b[:10]

array([864751430, 328965239, 387052877, 717196187, 193010287, 816293541,
       763287835, 563647349, 327254069, 495246847])

In [97]:
print(min(a), min(b))
print(np.argmin(a), np.argmin(b))
print(np.sum(a) + np.sum(b) + (SHAPE * min((np.argmin(a), np.argmin(b)))))

24 44
7116104 1651973
10002712564707759


In [110]:
a[0], a[29567], a[33767], a[2 * 29567], a[2 * 33767]

(np.int64(102022661),
 np.int64(85618108),
 np.int64(871224584),
 np.int64(316790843),
 np.int64(716361357))

In [98]:
def board_vis(a, b, digits_displayed = 2):
    combined = a[:, None] + b
    digs = int(np.log10(np.max(combined)))

    print(combined[0, :9].sum() + combined[1:, 8].sum() + combined[9, 9])
    combined//=(10 ** (digs - digits_displayed))

    print(pd.DataFrame(combined).to_string(index = False, header= False))
    return combined

#_ = board_vis(a, b, 3)

In [99]:
# splits = [((0, SHAPE), (0, SHAPE))]
# one_wide_splits = []

# while len(splits):
#     (a_low, a_high), (b_low, b_high) = splits[0]
#     #print('Initial Indicies:\n', (int(a_low), int(a_high)), (int(b_low), int(b_high)))
#     #print('One wide splits:\n', one_wide_splits)
#     #print('Splits:\n', splits)
#     #print()


#     a_local, b_local = a[a_low:a_high + 1], b[b_low:b_high + 1]
    
#     if (0, 0) == (a_local.argmin(), b_local.argmin()):
#         if a_high - a_low == 1 and b_high - b_low == 1:
#             second_a = a_local[1] + b_local[0]
#             second_b = a_local[0] + b_local[1]
#         elif a_high - a_low == 1:
#             second_a = a_local[1] + b_local[0]
#             second_b = a_local.min() + b_local[1:].min()
#         elif  b_high - b_low == 1:
#             second_a = a_local[1:].min() + b_local.min()
#             second_b = a_local[0] + b_local[1]
#         else:
#             second_a = a_local[1:].min() + b_local.min()
#             second_b = a_local.min() + b_local[1:].min()

#         if second_a < second_b:
#             a_min, b_min = a_low + 1 + np.argmin(a_local[1:]), b_low
#         else:
#             a_min, b_min = a_low, b_low + 1 + np.argmin(b_local[1:])
#     else:
#         a_min, b_min = a_local.argmin() + a_low, b_local.argmin() + b_low
    
#     splits = splits[1:]

#     if a_low == a_min :
#         one_wide_splits.append(((a_low, a_min), (b_low, b_min - 1)))
#     elif b_low == b_min:
#         one_wide_splits.append(((a_low, a_min - 1), (b_low, b_min)))
#     else:
#         splits.append(((a_low, a_min), (b_low, b_min)))

#     if a_high == a_min or b_high == b_min or a_min == SHAPE - 1 or b_min == SHAPE - 1:
#         one_wide_splits.append(((a_min, min(a_high, SHAPE -1)), (b_min, min(b_high, SHAPE - 1))))
#     else:
#         splits.append(((a_min, a_high), (b_min, b_high)))

    


In [100]:
# def sum_splits(one_wide_splits):
#     total = 0

#     for (a_low, a_high), (b_low, b_high) in one_wide_splits:
#         #print(int(a_low), int(a_high), int(b_low), int(b_high))
        

#         if a_low == a_high:
#             total += a[a_low] * (1 + b_high - b_low) + b[b_low:b_high + 1].sum()
#         else:
#             total += a[a_low:a_high + 1].sum() + b[b_low] * (1 + a_high - a_low)

#         #print(total)

#     return total

# sum_splits(one_wide_splits)


In [101]:
lower_bound = sum(a) + sum(b) + SHAPE * min(a) + SHAPE * min(b)
lower_bound

np.int64(9986193514707759)

In [102]:
def indexes_to_sum(indexes):
    total = 0
    for x, y in indexes:
        total += a[x] + b[y]
    return total

In [103]:
path = [(0, x) for x in range(5)] + [(x, 4) for x in range(1, 9)] + [(8, x) for x in range(5, 9)] + [(9, 8), (9, 9)]

indexes_to_sum(path)

np.int64(13389278727)

In [104]:
naive_path = a[0] * np.argmin(b) + \
             a[np.argmin(a)] * (SHAPE - np.argmin(b)) + \
             a.sum() + \
             b[np.argmin(b)] * np.argmin(a) +\
             b[SHAPE - 1] * (SHAPE - np.argmin(a)) +\
             b.sum()
naive_path

np.int64(11395256251387248)

In [105]:
rev_cumsum_a = np.concat([np.cumsum(a[::-1])[-2::-1], np.zeros(1, dtype = int)])
rev_cumsum_b = np.concat([np.cumsum(b[::-1])[-2::-1], np.zeros(1, dtype = int)])

In [106]:
# import heapq

# visited = set()
# frontier = []
# heapq.heappush(frontier, (a[0] + b[0], (0, 0), a[0] + b[0]))
# goal = False
# min_cost = np.min(a) + np.min(b)
# max_idx = (0, 0)
# max_idx_cost = 0

# while not goal:
#     cost, (x, y), total = heapq.heappop(frontier)
#     if (x, y) in visited:
#         continue

#     visited.add((x, y))

#     if (x, y) == (SHAPE - 1, SHAPE - 1):
#         print(total)
#         goal = True
 
#     if x + y > max_idx[0] + max_idx[1]:
#         max_idx = (x, y)
#         max_idx_cost = cost
#         if 10 * (x + y) % (SHAPE * 2) == 0:
#             print((x, y), cost, (x + y)/(2 * SHAPE))

    
#     if x < SHAPE - 1 and (x + 1, y) not in visited:
#         new_cost = total + a[x + 1] + b[y]
#         min_cost = new_cost + rev_cumsum_a[x + 1] + rev_cumsum_b[y] + (SHAPE - x - 1) * np.min(a[x + 1:]) + (SHAPE - y) * np.min(b[y:])
#         heapq.heappush(frontier, (min_cost , (x + 1, y), new_cost))
#     if y < SHAPE - 1 and (x, y + 1) not in visited:
#         new_cost = total + a[x] + b[y + 1]
#         min_cost = new_cost + rev_cumsum_a[x] + rev_cumsum_b[y + 1] + (SHAPE - x) * np.min(a[x:]) + (SHAPE - y - 1) * np.min(b[y + 1:])
#         heapq.heappush(frontier, (min_cost , (x, y + 1), new_cost))

# print(f'Fraction of nodes visited: {len(visited)/SHAPE**2}')
# print(f'Fraction of visited nodes belonging to eventual path: {2 * SHAPE/len(visited)}')